# Generated by Django 3.0.5 on 2020-04-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ages0_25', models.FloatField()),
                ('ages26_50', models.FloatField()),
                ('ages51_75', models.FloatField()),
                ('ages76_100', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('socialDistancing', models.FloatField()),
                ('annualAverage', models.FloatField()),
                ('infectiousDays', models.IntegerField()),
                ('firstHospitalizedCase', models.DateField()),
                ('hospitalization', models.FloatField()),
                ('ventilationNeed', models.FloatField()),
                ('icuNeed', models.FloatField()),
                ('averageHospitalLengthOfStay', models.IntegerField()),
                ('averageDaysInICU', models.IntegerField()),
                ('averageDaysOnVentilator', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('marketShare', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masks', models.IntegerField()),
                ('gloves', models.IntegerField()),
                ('ventilators', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('population', models.IntegerField()),
                ('boundaries', models.CharField(max_length=200)),
                ('ageDistribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age_distribution_of', to='hfamAPI.AgeDistribution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'Diagnosed'), ('2', 'Hospitalized'), ('3', 'Discharged')], default='1', max_length=15)),
                ('disease', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_of', to='hfamAPI.Disease')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfamAPI.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_of', to='hfamAPI.Inventory'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfamAPI.Region'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hfamAPI.Hospital')),
                ('timetable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_of', to='hfamAPI.TimeTable')),
            ],
        ),
    ]
