# Generated by Django 3.0.5 on 2020-04-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hfamAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hospitalized', models.IntegerField()),
                ('icu', models.IntegerField()),
                ('ventilated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictionInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('hospitalMarketShare', models.FloatField()),
                ('currentHospitalized', models.IntegerField()),
                ('dateFirstHospitalizedCase', models.DateField()),
                ('socialDistancing', models.FloatField()),
                ('hospitalizationPercent', models.FloatField()),
                ('icuNeedPercent', models.FloatField()),
                ('ventilationNeedPercent', models.FloatField()),
                ('infectiousDays', models.IntegerField()),
                ('averageHospitalLengthOfStay', models.IntegerField()),
                ('averageDaysInICU', models.IntegerField()),
                ('averageDaysOnVentilator', models.IntegerField()),
                ('numberOfDaysToProject', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='firstHospitalizedCase',
            new_name='dateFirstHospitalizedCase',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='marketShare',
            new_name='hospitalMarketShare',
        ),
        migrations.AddField(
            model_name='hospital',
            name='currentHospitalized',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PredictionOutputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admittedPatients', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_patients_of', to='hfamAPI.AdmittedPatients')),
                ('predictionInputs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_inputs_of', to='hfamAPI.PredictionInputs')),
            ],
        ),
    ]
