# Generated by Django 3.0.5 on 2020-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hfamAPI', '0002_auto_20200403_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospitalMarketShare',
            new_name='marketShare',
        ),
    ]
