# Generated by Django 3.0.5 on 2020-04-03 15:32

import datetime

import django.utils.timezone
import jsonfield.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('hfamAPI', '0003_auto_20200403_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='dateFirstHospitalizedCase',
            new_name='dateOfFirstHospitalizedCase',
        ),
        migrations.RenameField(
            model_name='predictioninputs',
            old_name='dateFirstHospitalizedCase',
            new_name='dateOfFirstHospitalizedCase',
        ),
        migrations.AddField(
            model_name='predictionoutputs',
            name='census',
            field=jsonfield.fields.JSONField(default=datetime.datetime(2020, 4, 3, 15, 32, 30, 753728, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionoutputs',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionoutputs',
            name='sir',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionoutputs',
            name='admittedPatients',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.DeleteModel(
            name='AdmittedPatients',
        ),
    ]
