# Generated by Django 3.0.5 on 2020-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfamAPI', '0005_hospital_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionoutputs',
            name='test',
            field=models.IntegerField(null=True),
        ),
    ]
