# Generated by Django 3.0.5 on 2020-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfamAPI', '0006_predictionoutputs_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='annualAverage',
        ),
        migrations.AddField(
            model_name='patient',
            name='previousDiseases',
            field=models.CharField(choices=[('1', 'Respiratory'), ('2', 'Heart'), ('3', 'Inflammatory')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='previousMedicine',
            field=models.TextField(null=True),
        ),
    ]
