# Generated by Django 3.0.5 on 2020-04-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfamAPI', '0007_auto_20200404_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='previousDiseases',
            field=models.CharField(choices=[('RESPITATORY', 'Respiratory'), ('HEART', 'Heart'), ('INFLAMMATORY', 'Inflammatory')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(choices=[('DIAGNOSED', 'Diagnosed'), ('HOSPITALIZED', 'Hospitalized'), ('DISCHARGED', 'Discharged')], default='DIAGNOSED', max_length=15),
        ),
    ]
