# Generated by Django 3.0.5 on 2020-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfamAPI', '0008_auto_20200404_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='admitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='cured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latLong',
            field=models.CharField(default='', max_length=50),
        ),
    ]
